language: go
go:
- '1.10'
- '1.11'
- master
env:
  - GO111MODULE=on
  global:
    secure: M5WX14Qmf3Zx14wlFEED+oCC3xFhBxEhHvRUv1DL7nkMaQ7Kx/k2eeYgIaRaUa02XC+Dg32JQ/gFL9wdWFL4YKV8SRYdSIhquIpy/JizXXItpDOXr+t+qozUn/j0d6P/8qhP14HnCp+BiXFSocaNMme+3gS0boz/6f2d3n3Jor+Zsb7uIy3tufIgrUzDPby8fcANTWYNXIqBpiR+PYi4ypoYWuwTNFrKnhuYPpjzGIqzxVk3Sxy200wzDpk3WmXThOEVS+CMA6DaIoolZVJUkDbF5H8fV95TMW0SvuJuHl6dsvlazoBKPPd4Ty3da+OmfPwVgeCeDmfRNRxJa2n0JDSh/lcnXPbwSnXuS41ezOEELhW68XdPweFEpHOcyuPUSqGuSrE6whpmaX11c/yYcuJtnP9Z3nqZrakJa1TPikYlSccCEwZ6ASelYM5IVM0DKQM3NpqKZlbl4HXW+NAcw0svJn8UfDD3RVml5Te2qAcAGzRg/coz9Yy+O/yH1DGNsHSAUqqVr2VbFgpgWkkOIEDqSHMNdEh42ppKGsnroWQvhzZP6fTSN6A/2oo13CnaPoz09o5818egpZ4KJdHQTVB1QWTF1pl3zZ/FGO3dCuhE7Clo1eFvkMi8E7OuLO11Dm1hrQsubAM6/6UEzkjEey/AOM3nKtnu1cbFgFgmNTs=
script: go test
